# Generated by Django 3.0.5 on 2020-05-09 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='var_goal',
            field=models.ManyToManyField(blank=True, related_name='var_goal', to=settings.AUTH_USER_MODEL),
        ),
    ]
