# Generated by Django 3.0.5 on 2020-05-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_auto_20200508_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
